# Generated by Django 5.0.6 on 2024-06-29 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('ART', 'Artificer'), ('BARB', 'Barbarian'), ('BARD', 'Bard'), ('CLRC', 'Cleric'), ('DRD', 'Druid'), ('FTR', 'Fighter'), ('MONK', 'Monk'), ('PLDN', 'Paladin'), ('RNGR', 'Ranger'), ('ROG', 'Rogue'), ('SORC', 'Sorcerer'), ('WRLK', 'Warlock'), ('WZRD', 'Wizard')], max_length=4)),
                ('_is_primery', models.BooleanField(verbose_name='is_primary')),
                ('level', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('_is_active', models.BooleanField(verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('_is_active', models.BooleanField(verbose_name='is_active')),
                ('level', models.SmallIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg_manager.player')),
            ],
        ),
    ]
