# Generated by Django 5.0.6 on 2024-07-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpg_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterclass",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rpg_manager.character",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="character",
            name="_is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.SmallIntegerField(default=0),
        ),
    ]
