# Generated by Django 5.0.6 on 2024-07-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rpg_manager",
            "0002_characterclass_archived_characterclass_character_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterclass",
            old_name="character",
            new_name="parent_character",
        ),
        migrations.RemoveField(model_name="characterclass", name="_is_primery",),
        migrations.AddField(
            model_name="character",
            name="primary_class",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rpg_manager.characterclass",
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="_is_primary",
            field=models.BooleanField(default=False, verbose_name="is_primary"),
        ),
    ]
